<?php

namespace AppBundle\Repository;

/**
 * MonEntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonEntiteRepository extends \Doctrine\ORM\EntityRepository
{
}
